name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --file Dockerfile -t ${{secrets.LOGIN_SERVER}}/gobackend:latest .
      
    - name: Docker login to azure container
      run: docker login -u ${{ secrets.DOCKER_AZURE_USERNAME }} -p ${{ secrets.DOCKER_AZURE_PASSWD }} ${{secrets.LOGIN_SERVER}}
    
    - name: Docker push to azure
      run: docker push ${{secrets.LOGIN_SERVER}}/gobackend:latest
